project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!HW/Proj/"
    - "!Grade/"

language: translate_jp.yml

website:
  favicon: Figs/favicon.png
  site-url: "https://www.jaysong.net/r4ps/"
  title: "R for Political Science"
  reader-mode: true
  search: true
  page-footer: 
    right:
      - text: "© 2025, Jaehyun Song"
      - icon: house-fill
        href: https://www.jaysong.net
      - icon: github
        href: https://github.com/JaehyunSong
  navbar:
    logo: Figs/logo.png
    search: true
    background: "#1955A6"
    pinned: true
    left:
      - sidebar:syllabus
      - sidebar:intro
      - sidebar:material-micro
      - sidebar:material-macro
      - sidebar:homework
    right: 
      - icon: terminal
        href: https://jupyter.cs.rcos.nii.ac.jp/
        target: _blank
      - icon: book
        href: https://www.jaysong.net/RBook/
        target: _blank
  sidebar:
    - id: syllabus
      title: "シラバス"
      style: "docked"
      contents: 
        - text: "[前期] ミクロ政治データ分析実習"
          href: syllabus/syllabus_micro.qmd
        - text: "[後期] マクロ政治データ分析実習"
          href: syllabus/syllabus_macro.qmd
        - text: "セッション情報"
          href: syllabus/session.qmd
    - id: intro
      title: "Rの使い方"
      style: "docked"
      contents:
        - intro/install.qmd
        - intro/rstudio.qmd
        - intro/filesystem.qmd
        - intro/project.qmd
        - intro/file.qmd
        - text: "パッケージ"
          href: intro/packages.qmd
        - intro/homework.qmd
        - intro/faq.qmd
    - id: material-micro
      title: "前期講義資料"
      style: "docked"
      contents:
        - materials/micro/introduction.qmd
        - materials/micro/r.qmd
        - materials/micro/basic.qmd
        - materials/micro/programming.qmd
        - materials/micro/quarto.qmd
        - materials/micro/dataset.qmd
        - materials/micro/datatype.qmd
        - materials/micro/datastructure.qmd
        - materials/micro/handling1.qmd
        - materials/micro/handling2.qmd
        - materials/micro/handling3.qmd
        - materials/micro/visualization1.qmd
        - materials/micro/visualization2.qmd
        - materials/micro/visualization3.qmd
    - id: material-macro
      title: "後期講義資料"
      style: "docked"
      contents:
        - materials/macro/introduction.qmd
        - materials/macro/research_design.qmd
        - materials/macro/descriptive_statistics.qmd
        - materials/macro/inference.qmd
        - materials/macro/nhts.qmd
        - materials/macro/association.qmd
        - materials/macro/regression1.qmd
        - materials/macro/regression2.qmd
        - materials/macro/reporting.qmd
        - materials/macro/logit.qmd
        - materials/macro/interaction.qmd
        - materials/macro/summary.qmd
    - id: homework
      title: "課題"
      style: "docked"
      contents:
         - intro/homework.qmd
         - section: "ミクロ"
           contents: 
             - text: "[前期] 第5回課題"
               href: HW/Micro_HW05.qmd
             - text: "[前期] 第10回課題"
               href: HW/Micro_HW10.qmd
             - text: "[前期] 第11回課題"
               href: HW/Micro_HW11.qmd
             - text: "[前期] 第13回課題"
               href: HW/Micro_HW13.qmd
             - text: "[前期] 第14回課題"
               href: "#"
             - text: "[前期] 期末レポート"
               href: HW/Micro_Final.qmd
         - section: "マクロ"
           contents:
             - text: "[後期] 第4回課題"
               #href: HW/Macro_HW04.qmd
             - text: "[後期] 第7回課題"
               #href: HW/Macro_HW07.qmd
             - text: "[後期] 第10回課題"
               #href: HW/Macro_HW10.qmd
             - text: "[後期] 第12回課題"
               #href: HW/Macro_HW12.qmd
             - text: "[後期] 期末レポート"
               #href: HW/Macro_Final.qmd
  google-analytics: "G-9TLN2VMPQD"

format:
  html:
    theme: 
      light: [a11y, r4ps.scss]
    toc-depth: 3
    link-external-newwindow: true
    code-annotations: hover
    mainfont: "Noto Sans JP"
    sansfont: "Noto Sans JP"
    monofont: "Noto Sans Mono"
    header-includes: |
      <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP&display=swap" rel="stylesheet"> 
      <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+Mono&display=swap" rel="stylesheet"> 

execute: 
  freeze: auto