---
title: "「ミクロ政治データ分析実習」第10回課題"
---

<center><a href="Data/Micro_HW10_Sample.html" class="btn btn-primary btn-lg" target="_blank" role="button"><i class="bi bi-window"></i> サンプルファイルの表示</a></center>

:::{.callout-important}
## 課題の取り組み方が分からない!

* 本サポートページのRの使い方 > [課題の取り組み方](../intro/homework.qmd)、または関大LMS内の解説動画を参照する。
* 本講義の課題は全てQuartoを使用する。使い方は「ミクロ政治データ分析実習」の第5回を参照すること。
* 分からないことがあったら、必ず宋・TAと相談すること。
:::

:::{.callout-important}
## 提出ファイルは`.html`ファイル（`.qmd`ファイルではない!!）

　たまに`.qmd`ファイルを提出したり、あるいは`.qmd`ファイルの拡張子を`.html`に変更して提出する場合があるが、この場合、**未提出**とみなす。実際、毎年これに該当するケースがある。提出する前に、提出するファイルを自分のPCで開き、サンプルファイルと同じ形式になっているかを確認すること。自分がLMSに提出したファイルはLMSの「マイレポート」からダウンロードすることができるため、もう一度確認してみるのも良し。
:::

**Step1:** LMSから課題用ファイル一式をダウンロードする。

- 課題用ファイル（`Micro_HW10.qmd`）、課題用データ（`Micro_HW10.csv`）

**Step2:** JDCat分析ツールを起動し、本講義用のプロジェクトを開く。

**Step3:** プロジェクト・フォルダーに課題用ファイル（`Micro_HW10.qmd`）をアップロードする。

**Step4:** プロジェクト・フォルダー内のデータ保存用フォルダーに課題用データ（`Micro_HW10.csv`）をアップロードする。

:::{.callout-important}
## ファイルのアップロード先に注意! 

　課題用ファイル（`.qmd`）はプロジェクト・フォルダ―の直にアップロードし、課題用データ（`.csv`）はプロジェクト・フォルダ―内の`Data`フォルダーに入れること。`Data`フォルダーに`.qmd`ファイルと`.csv`ファイル**両方**を入れている履修者がいるが、この場合、renderが出来ない場合がある（自分がファイルシステムに詳しいならコード内のパスを修正して対応することも可能）。つまり、`.qmd`フィアルと`.csv`ファイルを同じフォルダーに入れないこと。

　改めて強調するが、ファイルシステムの理解に自信がある（相対パス/絶対パスが書ける）ケースを除き、以下のようにアップロードすること。

- `.qmd`ファイル：プロジェクト・フォルダー（`プロジェクト名.Rproj`ファイルがある場所）にアップロード
- `.csv`ファイル：プロジェクト・フォルダーに`data`（または`Data`）フォルダーを作成し、そこにアップロード

　以上の内容は今後の課題でも同様である。
:::

**Step5:** 課題用ファイル（`Micro_HW10.qmd`）を開き、一旦、Renderしてみる。

**Step6:** 以下のボタンをクリックし、サンプルファイルを確認する。

<a href="Data/Micro_HW10_Sample.html" class="btn btn-primary btn-sm" target="_blank" role="button"><i class="bi bi-window"></i> サンプルファイルの表示</a>

**Step7:** サンプルファイルと同じ結果が得られるように課題用ファイルを修正する。

* 提出者の学籍番号・氏名の修正を忘れないこと。

**Step8:** 完成したら出力物（`.html`ファイル）を自分のPCにダウンロードする。

**Step9:** ダウンロードしたファイルをLMSに提出する。**提出する前にダウンロードした`.html`ファイルを開き、正しくダウンロードされているかを確認すること。**

:::{.callout-important}
## 課題を途中で中断し、再開した場合は...

　課題を途中で中断し、再開した場合、RStudioの右上の「Project:」欄が「(None)」になっているか確認すること。「(None)」のまま、あるいはプロジェクト名が課題用プロジェクト名と一致しない場合はメニューの File > Open Project から開くこと。プロジェクトの開き方は本サポートページの Rの使い方 > プロジェクト管理 から確認できる。
:::