---
title: "第5回課題"
---

:::{.callout-important}
## 課題の取り組み方が分からない!

* 本サポートページのRの使い方 > [課題の取り組み方](../intro/homework.qmd)、または関大LMS内の解説動画を参照する。
* 分からないことがあったら、必ず宋・TAと相談すること。
:::


:::{.callout-important}
## 提出ファイルは`.html`ファイル（`.qmd`ファイルではない!!）

　たまに`.qmd`ファイルを提出したり、あるいは`.qmd`ファイルの拡張子を`.html`に変更して提出する場合があるが、この場合、**未提出**とみなす。実際、毎年これに該当するケースがある。提出する前に、提出するファイルを自分のPCで開き、サンプルファイルと同じ形式になっているかを確認すること。自分がLMSに提出したファイルはLMSの「マイレポート」からダウンロードすることができるため、もう一度確認してみるのも良し。
:::

**Step1:** LMSから課題用ファイルをダウンロードする。

* 課題用ファイル（`Micro_HW05.qmd`）

**Step2:** NIIオンライン分析システムを起動し、課題用のプロジェクトを作成する。

**Step3:** プロジェクト・フォルダーに課題用ファイル（`Micro_HW05.qmd`）をアップロードする。

**Step4:** アップロードしたファイル（`Micro_HW05.qmd`）を開き、一旦、knitしてみる。

**Step5:** 以下のボタンをクリックし、サンプルファイルを確認する。

<a href="Data/Micro_HW05_Sample.html" class="btn btn-primary btn-sm" target="_blank" role="button"><i class="bi bi-window"></i> サンプルファイルの表示</a> <a href="Data/Micro_HW05_Sample.pdf" class="btn btn-primary btn-sm" target="_blank" role="button"><i class="bi bi-window"></i> 指示事項の表示</a>

**Step6:** サンプルファイルと同じ結果が得られるように課題用ファイルを修正する。

**Step7:** 完成したら出力物（`.html`ファイル）を自分のPCにダウンロードする。

**Step8:** ダウンロードしたファイルをLMSに提出する。**提出する前にダウンロードした`.html`ファイルを開き、正しくダウンロードされているかを確認すること。**

:::{.callout-important}
### 課題を途中で中断し、再開した場合は...

　課題を途中で中断し、再開した場合、RStudioの右上の「Project:」欄が「(None)」になっているか確認すること。「(None)」のまま、あるいはプロジェクト名が課題用プロジェクト名と一致しない場合はメニューの File > Open Project から開くこと。プロジェクトの開き方は本サポートページの Rの使い方 > プロジェクト管理 から確認できる。
:::