---
title: "「ミクロ政治データ分析実習」第14回課題"
---

**Step1:** LMSから課題用ファイル一式をダウンロードする。

* 課題用ファイル（`Micro_HW14.Rmd`）、課題用データ（`Micro_HW14.csv`）

**Step2:** NIIオンライン分析システムを起動し、課題用のプロジェクトを作成する。

**Step3:** プロジェクト・フォルダー内に`Data`フォルダーを作成する。

**Step4:** プロジェクト・フォルダーに課題用ファイル（`Micro_HW14.Rmd`）をアップロードする。

**Step5:** `Data`フォルダーに課題用データ（`Micro_HW14.csv`）をアップロードする。

:::{.callout-important}
### ファイルのアップロード先に注意!

　課題用ファイル（`.Rmd`）はプロジェクト・フォルダ―の直にアップロードし、課題用データ（`.csv`）はプロジェクト・フォルダ―内の`Data`フォルダーに入れること。多くの履修者が`Data`フォルダーに`.Rmd`ファイルと`.csv`ファイルを入れているが、この場合、Knitが出来ない場合がある（自分がファイルシステムに詳しいならコード内のパスを修正して対応することも可能）。
:::

**Step6:** 課題用ファイル（`Micro_HW14.Rmd`）を開き、一旦、Knitしてみる。

**Step7:** 以下のボタンをクリックし、サンプルファイルを確認する。

<a href="Data/MicroAnalysis_HW14.html" class="btn btn-primary btn-sm" target="_blank" role="button"><i class="bi bi-window"></i> サンプルファイルの表示</a>

**Step8:** サンプルファイルと同じ結果が得られるように課題用ファイルを修正する。

* 提出者の学籍番号・氏名の修正を忘れないこと。
* チャンク内の`# この行を削除し、コードを入力`の部分を削除し、コードを入力する。

**Step9:** 完成したら出力物（`.html`ファイル）を自分のPCにダウンロードする。

**Step10:** ダウンロードしたファイルをLMSに提出する。提出する前にダウンロードしたファイルを開き、正しくダウンロードされているかを確認すること。

**注意:** 課題の取り組み方が分からない場合、オフィスアワーなどを利用し担当教員と相談すること。

:::{.callout-important}
### 課題を途中で中断し、再開した場合は...

　課題を途中で中断し、再開した場合、RStudioの右上の「Project:」欄が「(None)」になっているか確認すること。「(None)」のまま、あるいはプロジェクト名が課題用プロジェクト名と一致しない場合はメニューの File > Open Project から開くこと。プロジェクトの開き方は本サポートページの Rの使い方 > プロジェクト管理 から確認できる。
:::